[package]
name = "rush"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.8"
log = { version = "0.4.29", features = ["serde", "std"] }
rustyline = { version = "18.0.0", features = ["with-fuzzy", "custom-bindings"] }
skim = "4"
rush-core = { path = "../rush-core" }
